// 08_REACT/DAY_1/myapp/src/Componenets/Login/Login.jsx
import React from 'react'

function Login() {
  return (
    <div><form>
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"/>
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1"/>
    </div>
    <div class="mb-3 form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1"/>
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form></div>
  )
}

export default Login

// 11_ANGULAR/my-app/src/app/login/login.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {

  msg:string = "Welcome to login page"
  value:boolean= true;
  num:Number=343

  loginImg:string = "https://cdn.pixabay.com/photo/2019/01/28/11/56/registration-3960205_1280.jpg"

  btnClick(){
    alert("Successfully Login🕸")
  }

}

<div class="row border border-2  p-5 w-100 justify-content-evenly">
    <div class="col-6">
        <img [src] = loginImg  width="100%" alt="">
    </div>
    <div class="col-6">
    
            <form class="m-3 p-3">

                <h1 class="m-3"><p>{{msg}}</p></h1><br><br>
                
                <div class="mb-3 w-50">
                  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                  <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
                <div class="mb-3 w-50">
                  <input type="password" class="form-control" id="exampleInputPassword1">
                </div>
                <div class="mb-3 form-check">
                  <input type="checkbox" class="form-check-input" id="exampleCheck1">
                  <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button (click)="btnClick()" routerLink="home" type="submit" class="btn btn-primary">Submit</button>
              </form><br><br><br>
    </div>
</div>
