// 11_ANGULAR/ANGULAR_2/e-cart-frontend/src/app/cart/cart.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../services/api.service';

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.css']
})
export class CartComponent implements OnInit {

  constructor(private api:ApiService){}
  cartItem:any=[]
  ngOnInit(): void {
    this.getCart()
  }

  getCart(){
    this.api.getCartAPI().subscribe({
      next:(res:any)=>{
        console.log(res);
        this.cartItem=res
        
      },
      error:(err:any)=>{
        console.log(err);
        
      }
    })
  }

  deleteCart(id:any){
    this.api.deleteCartProductAPI(id).subscribe({
      next:(res:any)=>{
        console.log(res);
        this.getCart()
        
      },
      error:(err:any)=>{
        console.log(err);
        
      }
    })
  }

  incrementCart(id:any){
    this.api.incrementCartProductAPI(id).subscribe({
      next:(res:any)=>{
        console.log(res);
        this.getCart()
        
      },
      error:(err:any)=>{
        console.log(err);
        
      }
    })
  }

  decrementCart(id:any){
    this.api.decrementCartProductAPI(id).subscribe({
      next:(res:any)=>{
        console.log(res);
        this.getCart()
        
      },
      error:(err:any)=>{
        console.log(err);
        
      }
    })
  }
  
  // totalPrice(){
  //   this.carttotal = this.cartItem.map({item:any}=>isNgTemplate.price).
  // }

}

<div class="container ">
    <div class="row p-4">
        <div class="col-9">
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Id</th>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col">Image</th>
            <th scope="col">Quantity</th>
            <th scope="col">Action</th>
            

          </tr>
        </thead>
        <tbody>
            <tr *ngFor="let cart of cartItem; let i=index">
                <th scope="row">{{i+1}}</th>
                <td>{{cart.id}}</td>
                <td>{{cart.title}}</td>
                <td>{{cart.price}}</td>
                <td><img [src]="cart.image" width="100px" alt=""></td>
                <td>
                    <div class="d-flex">
                        <button class="btn">-</button>
                        <input type="text" class="form-control" style="max-width: 45px;" [value]="cart.quantity " readonly>
                        <button class="btn">+</button>
                    </div>
                </td>
                <td><button (click)="deleteCart(cart.id)" class="btn"><i class="fa-solid fa-trash"></i></button></td>
                

            </tr>
        </tbody>
        
      </table>


</div>
<div class="col-3 card text-center ">
    <h1 class=""> Cart Summery</h1>
    <h2 class="">Total Price</h2>
    <div>
        <!-- Button trigger modal -->
<button type="button" class="btn btn-primary " data-bs-toggle="modal" data-bs-target="#exampleModal">
    Checkout
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Payement Form</h1>

          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <input type="text" name="name" id="" class="form-control m-1">
          <input type="text" name="address" id="" class="form-control m-1 ">
          <input type="text" name="phone number" id="" class="form-control m-1">
          <h3 class="m-1 p-2">Total Price :</h3>
          <div class="text-center">
            <button class="btn btn-success"> Make Payement</button>

          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          
        </div>
      </div>
    </div>
  </div>
    </div>
</div>
    
</div>
<div class="container text-center">
  <p>empty cart</p>

</div>

// 08_REACT/DAY_10/e-cart/src/Pages/Cart.jsx
import React, { useEffect } from 'react'
import { useSelector } from 'react-redux'

function Cart() {
  const cart = useSelector(state=>state.cartReducer)

  const [total,setTotal] = useState(0)

  useEffect(()=>{
    if(cart){
      setTotal(cart?.map(product=>product?.totalPrice).reduce((p1,p2)=>p1+p2))
    }
    else{
      setTotal(0)
    }
  },[])

  return (
    <div className='container d-flex justify-content-between p-5 m-5' style={{marginTop:"100px"}}>
     {
       cart?.length>0?
      <div className="row mt-5 ">
      <div className="col-lg-8 ">
        <table className='table shadow '>
          <thead>
            <tr>
              <th>#</th>
              <th>Titile</th>
              <th>Image</th>
              <th>Price</th>
              <th>Action</th>
            </tr>
     
          </thead>
          <tbody>
           {
             cart?.map((product,index)=>(
            <tr key={index}>
              <td>{index+1}</td>
              <td>{product.title}</td>
              <td><img style={{width:"300px",height:"300px"}} src={product.thumbnail} alt="" /></td>
              <td><input type="text" value={product.quantity} readOnly style={{width:"25px"}} /></td>
              <td>${product.totalPrice}</td>
              <td><button><i class="fa-solid fa-trash text-danger"></i></button></td>
            </tr>))
            }
          </tbody>
        </table>

        <div>
          <button>Empty Cart</button>
          <button>Shop More</button>
        </div>
      </div>
     </div>
:0}
  <div className='col-lg-3 '>
      <div className='container border border rounded shadow mt5 p-3 w-100'>
        
        <h1>Cart Summary</h1>
        <h4>Total Products</h4>
        <h5>Total: <span className='text-danger fw-bolder'>$1892</span></h5>
        <button className='btn btn-success m-3 rounded'>Checkout</button>
      </div>
     </div>
     <div></div>

    </div>
  )
}

export default Cart
